language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- make publish github
env:
  global:
    secure: aIqU6WIhIt4cfcvyCOseQLda/9sZu4zNFu/VWTgv0L+IXp43P+gJEaE2DOGAjeA2fBbOKWiME6/MzcQY+E4ftElCF+iNTumeKzmd9oz4Qg26eak53Za4jBLWy/8Sa1CXEUiuaWLdPa+SKhgbpc/MLYVnNNr1jbUS7+KzhKnV6fEoTW2XGphj/o7xTk4doBRwb3itwismlMSQZFKF+PSHPdeqXftB83EehKEx/kJvqTXvhg9vosbxffQhqd8JFAQK+66PVGnn4vQUrdRzWL+OhN02Crd6cPD0nYY3yxSlI9mDF7Hmsmx57xgOFtB9jfA0bzC9Q5Ic9qnzdmIM439G32lo8PXqLa1b6+f+d+NzKbSu+adBqWmeRy7dKx/GsHb1Ja+3Roty4SMXdWrPUfuE18WT4OVouAVGNMaYz5swQ5cgGzOCMGuVGxb8BkGEimV/AAYBtNTLaRunaGWBVGTCURr8fkXEdKFmpJfMS2SFCazuiPiMM5V9IK07Zk9UxYZSp/sAB7f2es4GgdLZfeCjcTU/YMFOIQhESIqy03sWhdNzdRNWhuwJU0xBgE5kvOu6rHbut9wPcyTL7x7AyOaiTIox7LxtPnqXaui3U3h9OujjRGsK78v6C7Gx28RLzLc7Cw8lu7Os3RW0Ze5FqpuX+KNJYbYdUw1Tp6XvHpB5pw8=
