language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- make publish github
env:
  global:
    secure: Lz+xuK61tKxoE2jjNTquzScBPYSeMRu+K3g1rrtFauWVsHcEao4X1gl/G4rP1OFOMqRcomt5xsCMCCsEsS8E1Pv96fyHxKnsz8UheSFt2vmCfthQZZ+brWeoxgz7On6IjW1tw6pAlpqi6g7FO2jscngNfGr54h33HjubdOGRNS02S2aZobuhI5s8vZxeiPiObzavXiOC2nop/PZH9ydDhm3GJu1U/kg+n3Ho5wUr99TEIap4P4VH/Gy9YaD+ZMNu+Z24e8fdICRc4nBt4CRIfSA+2vST/oecEDG/drWWCayUZlEbPYzAIek8XoLq00NCGV5PmeDT16cOlDXRi/AfnP9oQOJLGii+w+u1r3n7nntXfq3JsSEg9HeTEa2YiNeiXNBSEBRnwqWO1u8f1wcSF0aqUzUi8Ea12ohv5m7eLcTlnwbNc+90G5R0OT13Ct9eG30CcYrFB7cQA4MSxyu5i47wpFymUHYo0XhvuroELNe9GRE+WKgwOuB8C3KyHzthFTKHYdAzxAjClJhOs10uK1b3ICz1SS/y5NJaaekzSGdnbBcSJzXhuzfpFbQBe3H0zOffsH4XtoXUkltsxM0Od3Zl3ubNcUcgvVivR4Wdesasp2OV8u+jjkcV0iOy9nhQK3b1FB8uJGRrUu+oj0DI5d3IHBK5yNrJ1kK6H79xOA0=
